export const defaultTemplates = [
  {
    id: "tpl_hollywood_35mm",
    title: "Hollywood 35mm",
    prompt: "A lone detective in a dark trench coat standing under a flickering streetlamp in the pouring rain, 35mm film grain, anamorphic lens flare, neo-noir moody volumetric lighting, slow dolly zoom",
    model: "wan-2.1",
    aspectRatio: "16:9",
    category: "Cinematic",
  },
  {
    id: "tpl_hypercar_drift",
    title: "Hypercar Drift",
    prompt: "A matte-black aerodynamic hypercar drifting on a wet alpine mountain road at golden hour, volumetric tire smoke, low-angle tracking camera, 8k photorealistic motion dynamics",
    model: "kling-1.5",
    aspectRatio: "16:9",
    category: "Automotive",
  },
  {
    id: "tpl_scifi_megacity",
    title: "Cyberpunk Megacity",
    prompt: "Futuristic flying vehicles navigating between colossal holographic skyscrapers in a rainy cyberpunk metropolis, volumetric neon haze, sweeping drone shot, photorealistic reflections",
    model: "wan-2.1",
    aspectRatio: "16:9",
    category: "Sci-Fi",
  },
  {
    id: "tpl_character_acting",
    title: "Emotional Character",
    prompt: "Dramatic 85mm portrait of an astronaut looking at an alien sunrise through their visor, emotional tears reflecting golden light, subtle realistic micro-expressions, 8k master cinematography",
    model: "minimax",
    aspectRatio: "16:9",
    category: "Storytelling",
  },
  {
    id: "tpl_bbc_nature",
    title: "BBC Wildlife Macro",
    prompt: "Macro 120fps slow-motion tracking shot of an iridescent emerald hummingbird hovering near an exotic rainforest orchid, morning dew droplet refraction, shallow depth of field",
    model: "wan-2.1",
    aspectRatio: "16:9",
    category: "Nature",
  },
  {
    id: "tpl_martial_arts",
    title: "Bamboo Martial Arts",
    prompt: "Two skilled martial artists sparring atop a mist-covered bamboo forest in ancient Kyoto, realistic fluid physical combat, flowing silk robes, cinematic slow motion",
    model: "kling-1.5",
    aspectRatio: "16:9",
    category: "Action",
  },
  {
    id: "tpl_luxury_perfume",
    title: "Luxury Commercial",
    prompt: "Golden liquid droplets defying gravity in a sunlit minimalist architectural studio, crystal fragrance bottle rotating smoothly, caustic light patterns, high-fashion aesthetic",
    model: "seedance-2.0",
    aspectRatio: "16:9",
    category: "Commercial",
  },
  {
    id: "tpl_anime_action",
    title: "Anime Rooftop Run",
    prompt: "A cyberpunk anime heroine with glowing turquoise hair running across skyscrapers in Neo-Tokyo, speed lines, dynamic manga camera angles, vivid cel-shaded lighting",
    model: "seedance-2.0",
    aspectRatio: "16:9",
    category: "Anime",
  },
  {
    id: "tpl_retro_vhs",
    title: "1984 Retro VHS",
    prompt: "Teenagers riding BMX bikes down a sun-drenched suburban California street in 1984, authentic VHS tracking static lines, warm chromatic aberration, nostalgic golden hour",
    model: "minimax",
    aspectRatio: "16:9",
    category: "Vintage",
  },
  {
    id: "tpl_bioluminescence",
    title: "Deep Sea Behemoth",
    prompt: "A giant celestial whale swimming through deep dark ocean water, glowing turquoise and violet bioluminescent patterns on its skin, gentle drifting marine snow particles",
    model: "wan-2.1",
    aspectRatio: "16:9",
    category: "Fantasy",
  },
  {
    id: "tpl_streetwear_ugc",
    title: "SoHo Street Fashion",
    prompt: "High-energy handheld camera video of a stylish model walking down SoHo New York in oversized streetwear, natural daylight, authentic lens flare, smooth gimbal motion",
    model: "seedance-mini",
    aspectRatio: "9:16",
    category: "Social UGC",
  },
  {
    id: "tpl_dragon_flight",
    title: "Obsidian Dragon",
    prompt: "An ancient obsidian dragon gliding over jagged snow-covered mountain peaks at twilight, volumetric clouds parting around its wings, epic scale aerial cinematography",
    model: "wan-2.1",
    aspectRatio: "16:9",
    category: "Fantasy",
  },
];
